name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build ./api -t ag-api:$GITHUB_RUN_ID
    - name: Lint
      run: docker run ag-api:$GITHUB_RUN_ID npm run lint
    - name: Run tests
      run: docker run ag-api:$GITHUB_RUN_ID npm run test

  build-ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build ./ui -f ./ui/Dockerfile.dev -t ag-ui:$GITHUB_RUN_ID
    - name: Lint
      run: docker run ag-ui:$GITHUB_RUN_ID yarn lint
    - name: Run tests
      run: docker run ag-ui:$GITHUB_RUN_ID yarn test
    
