name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . -f ./Dockerfile.dev -t ag-ui:$GITHUB_RUN_ID
    - name: Lint
      run: docker run ag-ui:$GITHUB_RUN_ID yarn lint
    - name: Run tests
      run: docker run ag-ui:$GITHUB_RUN_ID yarn test
    
