name: Deploy

on: workflow_dispatch

jobs:

  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: https://${{ env.APP_NAME }}.herokuapp.com
          usedocker: true
          branch: ${GITHUB_REF}
          delay: 30
        env: 
          APP_NAME: ag-2021-ui